### ISSUE TITLE
Add docker container

### ISSUE THREAD

**Issue by Hacksore** [ajchili/mock-me#5]
that way you can just give it to a cloud provider (railway, fly.io, aws, etc) to run or even run it locally and use [CF tunnels](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/) to get an ephemeral URL.

i want
```
docker run ajchili/mock-me
```

kthxbai, i can help with this maybe™

**Comment by ajchili** [comment]
Seems like a reasonable thing to do.

Currently there are some assumptions made by `mock-me` with regards to the environment which it runs in which would need to be updated.

- `asset` assumes that the `yjs` server is accessible via the same domain, this may generally be true but exposing a mechanism to control this via environment variables would be nice
- `asset` is hosted with an `httpd` server, not sure how to pass environment variables within this environment
- the `yjs` server is just a docker container that runs `npx`, that is extremely brittle and likely should become an actual server again
    - this could aide in the above updates by allowing the `asset` code to be distributed by the server itself rather than a separate `httpd` server

This list is likely not exhaustive but it is a starting point 🤷

**Comment by Hacksore** [comment]
> [!WARNING]
> **IN COMING YAP 🗣️**

I was interested in "how do you run more than one thing in a docker container".

Looks like you can do any of the following to run more than one thing.
- [Use a wrapper script](https://docs.docker.com/config/containers/multi-service_container/#use-a-wrapper-script)
- [Use Bash job controls](https://docs.docker.com/config/containers/multi-service_container/#use-bash-job-controls)
- [Use a process manager](https://docs.docker.com/config/containers/multi-service_container/#use-a-process-manager)

So if you just create a real backend API server you can programmatically control the starting of a node server that:

- runs YJS
- servers static assets
- in the future api routes?

Then we just need a single container and can do the "docker run" stuffz.

This like you said needs control and since we are doing a static/SPA there is not a good way to pass this. We can do build time things with `VITE_*` but we need to figure this part out.
https://github.com/ajchili/mock-me/blob/299590697ceda443b27255e188c1cf38d4a70b03/packages/asset/src/components/Editor/Editor.tsx#L74

**Comment by ajchili** [comment]
Alright, I have spent some time on this, `ajchili/mock-me` is now published to [DockerHub](https://hub.docker.com/repository/docker/ajchili/mock-me/general).

You can just run `docker run -p 1234:1234 ajchili/mock-me` to get started.

------

This does not fully solve all of the problems listed above. Namely, `asset` now assumes that the express server is running on port `1234`. I think I will close this issue and create a new one to address that.

**Comment by ajchili** [comment]
Docker image is resolved, additional work captured in #7. Closing.
